### ISSUE TITLE
Versioning scheme?

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats-mtl#37]
We should commit a versioning scheme pre-1.0.

I think going with no changes in patch versions and breakages in minor versions seems ideal for now. We should also document this somewhere :)

**Comment by SystemFw** [comment]
Could you define "changes" and "breakages" here?
Is it bincompat, source compat or something else?

**Comment by LukaJCB** [comment]
Sorry, wrote that in a bit of a hurry, no binary or source incompatible changes in patch versions, but okay for minor versions is what I meant :)

**Comment by kailuowang** [comment]
if we promise no binary breaking changes in patch, do we need to setup mima? I am okay with that but just not sure if that's necessary and there maybe cases where we want to fix a bug in a binary breaking way.  
If we see 1.0 coming within a year, I'd propose we just use the same versioning scheme as cats-effect,  i.e. `0.Minor`, without patch versions. Keep it simple unless we see the need otherwise.
